### ISSUE TITLE
Incorrect judgement for slide body

### ISSUE THREAD

**Issue by Catty2014** [LumpBloom7/osu-maimai#651]
According to https://www.bilibili.com/opus/694985211225571337, slide body is judged at last segment rather than slide tail.

We can use official beatmap "Southern Cross"(Re:Master) to verify this: 
- slip the biggest crossing slide to last segment at "The **moment** of yesterday when we lived is never waste." 
  1. on official arcade machine we could earn "just perfect" 
  2. but in osu!sentakki only "good fast" is given.

However I didn't check the code for this, please let me know if the implementation is actually correct.

**Comment by LumpBloom7** [comment]
I presume you meant "segment before the last" when you say last segment, right? Because the last segment == tail in my vocabulary.

Skimming through the slide sections I don't see any mention that the slide is judged at "n-1" segment. (maybe my chinese skills are degraded)
Maybe show me exactly which paragraph, or better yet a side by side video comparison.

**Comment by XIAA25** [comment]
If I’m not mistaken, I think @Catty2014 means that the slide is judged when at the transition between the second to last and last segment of a slide.

**Comment by LumpBloom7** [comment]
I could interpret that in 2 ways:
1. The judgements occur before the last segment / tail. I feel that this doesnt make a lot of sense.
2. The judgements occur upon entering the detection region of the tail segment (which is not a point but an area). This is already done in sentakki, albeit with different detection regions due to sentakki not using the sensors defined on the arcade hardwarr. 

@Catty2014 will need to clarify the difference or at least show the exact difference. They can alternatively make a compelling argument for why the current sentakki behavior is "bugged". (discord may be more convenient for a discussion on this) 

As it stands, the current sentakki implementation is not bugged and is "by design". Not completing the slide means not completing the slide.

**Comment by Catty2014** [comment]
In original text (https://www.bilibili.com/opus/694985211225571337) it says “Slide判定的正解帧为引导星星进入Slide最后一个判定区的时间。” (The solution frame of slide is the time you slip the star **into** last judging area.)

In the following description, "edge" means the edge between last segment and former. 

Still taking Southern Cross for example:
- lyric: The moment of yesterday when we lived is never waste.
- On arcade: slip the star to the edge at "The [**moment**] of yesterday when we lived is never waste" get "perfect".
- On sentakki: slip the star to the edge at "The moment of yesterday when we lived is never [**waste**]" even get "early good".

I'll record a video soon to demonstrate the difference. However I have no access to discord due to network restriction. I'm glad to use any communication platform if I could access.

**Comment by LumpBloom7** [comment]
Thank you for the clarification. The problem can be summed up as “following the stars perfectly may still punish players on slow slides”.

This is an issue I definitely recall solving in #608, by accounting for the sensor radius during judgement. Double-checking it, it definitely is doing the job correctly. 

I presume you are using a build based on your fork, which [absolutely does have the appropriate fix](https://github.com/Catty2014/sentakki/blob/master/osu.Game.Rulesets.Sentakki/Objects/Drawables/DrawableSlideBody.cs#L230-L234), so there should not be an issue there.

Here's footage showing the behaviour in action. (The star turns green as soon as it crosses into the detection radius, indicating that it is a perfect judgement will be given)

https://github.com/user-attachments/assets/4dcea759-f5f1-48c8-aa5d-e51f3ed6025f

However, a notable observation is that it uses the star's centre as the cross-over point. I don't think this is a bug in a technical sense, but maybe it makes more sense to consider the star visual area?

PS: Investigating this, it seems that while my `master` branch on my repo has the fix. The `simai-import` branch somehow doesn't have the same fix, despite merging master into it many times, so I'm guessing a merge conflict went fucky. If you were building off of that branch then yes there would not have been any attempt to avoid the issue. I'll fix that.

**Comment by Catty2014** [comment]
Yeah I build from `simai-import` branch (which is what I once create my fork for).
Thank you for your work!

**Comment by LumpBloom7** [comment]
`simai-import` branch on this repo should be good for use now.

Thanks for making me aware of the problem.
